### ISSUE TITLE
Old image? Agent / Notebook on kubernetes not starting (memory-limit not set)

### ISSUE THREAD

**Issue by OskarHandmark** [backtick-se/cowait#188]
- `memory` / `cpu` may not be null
- `memory_limit` / `cpu_limit` Unknown field

Same issue for `cowait agent` and `cowait notebook`.
Looks to me like it's running on an old image.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/cowait/cowait/exec.py", line 45, in <module>
    asyncio.run(main())
  File "/opt/conda/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/var/cowait/cowait/exec.py", line 27, in main
    taskdef = env_get_task_definition()
  File "/var/cowait/cowait/worker/env.py", line 24, in env_get_task_definition
    return TaskDefinition.deserialize(taskdef)
  File "/var/cowait/cowait/tasks/definition.py", line 107, in deserialize
    return TaskDefinitionSchema().load(taskdef)
  File "/opt/conda/lib/python3.7/site-packages/marshmallow/schema.py", line 724, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/opt/conda/lib/python3.7/site-packages/marshmallow/schema.py", line 905, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'memory': ['Field may not be null.'], 'cpu': ['Field may not be null.'], 'memory_limit': ['Unknown field.'], 'cpu_limit': ['Unknown field.']}
```

**Comment by johanhenriksson** [comment]
I think we need to publish a new image, the latest `cowait/task` is tracking 0.3.2, not the master branch.

Building the base image locally should fix this problem
