### ISSUE TITLE
Improve cli:`cowait cluster` 

### ISSUE THREAD

**Issue by OskarHandmark** [backtick-se/cowait#305]
Improve the `cowait cluster` cli so it's a bit more intuitive. Perhaps include some examples in the the `--help` output.

```shell
$ cowait cluster

Usage: cowait cluster [OPTIONS] COMMAND [ARGS]...

  cluster management

Options:
  --help  Show this message and exit.

Commands:
  add          add new cluster
  default      default cluster name
  get          describe cluster
  ls           list all clusters
  rm           remove cluster
  set-default  set default cluster
```

```shell
$ cowait cluster add --help
Usage: cowait cluster add [OPTIONS] NAME

  add new cluster

Options:
  --type TEXT        cluster provider type
  -o, --option TEXT  specify cluster provider option
  --help             Show this message and exit.
```

```shell
$ cowait cluster add hello
Traceback (most recent call last):
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/bin/cowait", line 8, in <module>
    sys.exit(main())
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/cowait/__main__.py", line 14, in main
    app(obj=config)
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ohandmark/Library/Caches/pypoetry/virtualenvs/demo-zWrIhaRv-py3.8/lib/python3.8/site-packages/cowait/cli/app/cluster.py", line 47, in add
    cowait.cli.cluster_add(ctx.obj, name, type.lower(), **parse_input_list(option))
AttributeError: 'NoneType' object has no attribute 'lower'```

Aha, maybe `type` is required

```shell
$ cowait cluster add --type kubernetes hello
Error: context option must be provided when creating kubernetes clusters.
```

What is this context option? `-o`?  What should it be?

```
  -o, --option TEXT  specify cluster provider option
```

**Comment by johanhenriksson** [comment]
The `--option` parameter is used to set options on the cluster definition :) 

`context` is the name of the kubernetes context to use for the cluster. It's required because omitting it would be equivalent to just using the built-in `--cluster kubernetes`

Some other examples:

```
clusters:
  dev:
    type: kubernetes
    context: backtick-hq
    domain: hq.backtick.se
    router: traefik2
    traefik2:
      certresolver: default
```

Since they differ by cluster type, it might be a better idea to add subcommands to add clusters of different types, e.g. `cowait cluster add kubernetes <context name> --domain=hq.backtick.se`

**Comment by OskarHandmark** [comment]
I see. Makes sense :)

I believe it's hard for new users to understand this. I don't think it's obvious that `--option` is "repeatable" and what the possible inputs could be. Perhaps this is just a documentation thing. 

Couldn't we just be explicit about the different options that are available? i.e instead of `--option`, show which options are available. i.e:

```
$ cowait cluster add --help
Usage: cowait cluster add [OPTIONS] NAME

  add new cluster

Options:
  --type TEXT        cluster provider type
  --router TEXT     router to use e.g `traefik2`
  --domain TEXT   kubernetes domain
  --help             Show this message and exit.
```

I agree with `cowait cluster add kubernetes backtick-hq --domain=hq.backtick.se`, looks nice 👍

**Comment by OskarHandmark** [comment]
Also #126
